/**
 * MobileCredStore - REST/Krypto-Backend für Obsidian Mobile (ADR-0003.
 Erweiterung, ADR-0009-Follow-up): Auf mobile gibt es kein Electron
 * safeStorage; stattdessen WebCrypto AES-GCM 256 mit einem device-bound
 * Key (non-extractable, generated by generateKey), der in IndexedDB
 * persistiert. Das device-key bleibt im App-Container (iOS Keychain-
 * Schutz via WebView-Sandbox); ins data.json geht nur der Ciphertext.
 *
 * ADR-0003-Invariante bleibt fail-closed: Ohne Key (webcrypto fehlt /
 * IndexedDB nicht verfügbar) wird NICHT persistiert, save() wirft
 * EncryptionUnavailableError analog dem Desktop-CredStore.
 *
 * Identische IO wie CredStore (save/load/clear/clearAll + Session-Spiegel),
 * damit das I/O-Upgrade im Plugin-Wiring ausgetauscht werden kann.
 */

export interface DeviceKeyStore {
  /** Device-key laden; null wenn nicht vorhanden. */
  load(): Promise<CryptoKey | null>;
  /** Device-key speichern (idempotent, gleicher Key überschreibt sich selbst). */
  save(key: CryptoKey): Promise<void>;
}

const DB_NAME = "iserv-credstore";
const DB_VERSION = 1;
const STORE_NAME = "keys";
const KEY_ID = "mobile-cred-key";

/** IndexedDB-KeyStore: hält den AES-GCM-Key non-extractable. */
export class IndexedDbKeyStore implements DeviceKeyStore {
  private db: IDBDatabase | null = null;

  private openDb(): Promise<IDBDatabase> {
    if (this.db) return Promise.resolve(this.db);
    return new Promise((resolve, reject) => {
      const req = indexedDB!.open(DB_NAME, DB_VERSION);
      req.onupgradeneeded = () => {
        req.result.createObjectStore(STORE_NAME);
      };
      req.onsuccess = () => {
        this.db = req.result;
        resolve(this.db);
      };
      req.onerror = () => reject(req.error ?? new Error("indexedDB open fehlgeschlagen"));
    });
  }

  async load(): Promise<CryptoKey | null> {
    const db = await this.openDb();
    return new Promise((resolve, reject) => {
      const tx = this.db!.transaction(STORE_NAME, "readonly");
      const req = tx.objectStore(STORE_NAME).get(KEY_ID);
      req.onsuccess = () => resolve((req.result as CryptoKey | undefined) ?? null);
      req.onerror = () => reject(req.error ?? new Error("indexedDB get fehlgeschlagen"));
    });
  }

  async save(key: CryptoKey): Promise<void> {
    const db = await this.openDb();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(STORE_NAME, "readwrite");
      tx.objectStore(STORE_NAME).put(key, KEY_ID);
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error ?? new Error("indexedDB put fehlgeschlagen"));
    });
  }
}

/** ADR-0003-Genossin: fail-closed, kein Persist ohne funktionale Krypto. */
export class MobileEncryptionUnavailableError extends Error {
  constructor(reason: string) {
    super(
      `Credential-Speicherung auf mobile nicht möglich: ${reason}. ` +
        "Das Plugin speichert Credentials NUR verschlüsselt (fail-closed, ADR-0003). " +
        "Prüfe, dass es sich um Obsidian Mobile 1.6+ handelt (WebCrypto + IndexedDB)."
    );
    this.name = "MobileEncryptionUnavailableError";
  }
}

const CRED_KEY = "_credentials";
const SESSION_KEY = "_session";
const IV_BYTES = 12;
const SESSION_TTL_MS = 90 * 24 * 60 * 60 * 1000; // 90 Tage

interface EncryptedEntry {
  iv: string; // base64
  ct: string; // base64
  createdAt: number;
}

export class MobileCredStore {
  private plugin: { loadData(): Promise<Record<string, unknown>>; saveData(data: Record<string, unknown>): Promise<void> };
  private keyStore: DeviceKeyStore;
  private subtle: SubtleCrypto;
  private cachedKey: CryptoKey | null = null;

  constructor(
    plugin: { loadData(): Promise<Record<string, unknown>>; saveData(data: Record<string, unknown>): Promise<void> },
    keyStore: DeviceKeyStore,
    subtle: SubtleCrypto
  ) {
    this.plugin = plugin;
    this.keyStore = keyStore;
    this.subtle = subtle;
  }

  /** Fail-closed: kein key → kein Persist (analog CredStore.assertEncryptionAvailable). */
  private async assertKey(): Promise<CryptoKey> {
    if (this.cachedKey) return this.cachedKey;
    let key = await this.keyStore.load();
    if (!key) {
      // device-key NON-extractable erzeugen — kann das Gerät nie verlassen.
      try {
        key = await this.subtle.generateKey(
          { name: "AES-GCM", length: 256 },
          false,
          ["encrypt", "decrypt"]
        );
        await this.keyStore.save(key);
      } catch (err) {
        throw new MobileEncryptionUnavailableError(
          `Device-Key konnte nicht erzeugt werden: ${String(err).slice(0, 80)}`
        );
      }
    }
    this.cachedKey = key;
    return key;
  }

  private async encryptToString(plain: string): Promise<EncryptedEntry> {
    const key = await this.assertKey();
    const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
    const ct = await this.subtle.encrypt(
      { name: "AES-GCM", iv },
      key,
      new TextEncoder().encode(plain)
    );
    return { iv: btoa(String.fromCharCode(...iv)), ct: bufToB64(new Uint8Array(ct)), createdAt: Date.now() };
  }

  private async decryptEntry(entry: EncryptedEntry): Promise<string> {
    const key = await this.assertKey();
    const iv = b64ToUint8(entry.iv);
    try {
      const pt = await this.subtle.decrypt(
        { name: "AES-GCM", iv },
        key,
        b64ToUint8(entry.ct)
      );
      return new TextDecoder().decode(pt);
    } catch {
      throw new MobileEncryptionUnavailableError(
        "Eintrag konnte nicht entschlüsselt werden (Anderes device oder gelöschter Key)."
      );
    }
  }

  async save(key: string, value: string): Promise<void> {
    const data = await this.plugin.loadData();
    const store = (data[CRED_KEY] as Record<string, EncryptedEntry>) ?? {};
    store[key] = await this.encryptToString(value);
    data[CRED_KEY] = store;
    await this.plugin.saveData(data);
  }

  async load(key: string): Promise<string | null> {
    const data = await this.plugin.loadData();
    const store = (data[CRED_KEY] as Record<string, EncryptedEntry>) ?? {};
    const entry = store[key];
    if (!entry) return null;
    return await this.decryptEntry(entry);
  }

  async clear(key: string): Promise<void> {
    const data = await this.plugin.loadData();
    const store = (data[CRED_KEY] as Record<string, EncryptedEntry>) ?? {};
    delete store[key];
    data[CRED_KEY] = store;
    await this.plugin.saveData(data);
  }

  async clearAll(): Promise<void> {
    const data = await this.plugin.loadData();
    data[CRED_KEY] = {};
    await this.plugin.saveData(data);
  }

  // ---- session-spiegel (analog CredStore.saveSession/loadSession/clearSession) ----

  async saveSession(cookieValue: string): Promise<void> {
    await this.save(SESSION_KEY, JSON.stringify({ v: cookieValue, at: Date.now() }));
  }

  async loadSession(): Promise<string | null> {
    try {
      const raw = await this.load(SESSION_KEY);
      if (!raw) return null;
      const parsed = JSON.parse(raw) as { v: string; at: number };
      if (Date.now() - parsed.at > SESSION_TTL_MS) return null;
      return parsed.v;
    } catch (err) {
      if (err instanceof MobileEncryptionUnavailableError) return null;
      throw err;
    }
  }

  async clearSession(): Promise<void> {
    await this.clear(SESSION_KEY);
  }
}

function b64ToUint8(b64: string): Uint8Array<ArrayBuffer> {
  const bin = atob(b64);
  const out = new Uint8Array(new ArrayBuffer(bin.length));
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function bufToB64(bytes: Uint8Array): string {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}
